### ISSUE TITLE
Not recognised by Windows 10

### ISSUE THREAD

**Issue by deltawasp** [adafruit/Adafruit-PiUART-PCB#1]
My unit refuses to work with Windows 10, I have tried 2 separate PC's, 3 different Pis and a number of USB cables. At no point is the unit recognised.

It powers the Pi and I get a green LED.

I have enabled Shell/Serial as per instructions.

Is this a known issue? The only documentation I can find for Windows seems to cover XP.

**Comment by ladyada** [comment]
hiya please use the adafruit forums for tech support :)

**Comment by deltawasp** [comment]
Any chance of a link, I'm not familiar with your forums. Thanks.

**Comment by ladyada** [comment]
https://forums.adafruit.com/
